version: '3'

tasks:
  gen:
    desc: Generate gRPC client and server stubs and protocol buffer files
    # generates:
    #   - ./internal/outbound/grpc/**/*.pb.go
    cmds:
      - >
        protoc --go_out=. \
               --go_opt=paths=source_relative \
               --go-grpc_out=. \
               --go-grpc_opt=paths=source_relative \
               ./micro/lms/service.proto
      - mv ./micro/lms/service{,_grpc}.pb.go ./micro/lms/service/
