app:
  env: dev
  features:
    money_transfer: true
    tx_analytics: false
  rules:
    discount_eligibility_duration: 1800h # 6 months
    course_code_length_min: 6
    course_code_length_max: 6


logger:
  level: "debug"


database:
  host: "localhost"
  port: 5432
  username: "myuser"
  password: "mypassword"
  # name: "mydb" # each service has a different database name


http:
  host: "localhost"
  port: 8080


kafka:
  group: "mygroup"
  topics:
    - "topic1"
  brokers:
    - "localhost:9092"


metrics:
  filepath: "/var/log/myapp/foo.log"


services:
  default:
    host: "localhost"
    port: 50051


s3:
  client:
    max_retries: 5
  bucket_name: "test-bucket"
  object_key: "test-object"

grpc:
  client:
    timeout: 5